### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by gustavogino** [elDimasX/Antivirus#2]
Olá elDimasX, vi seu github e achei muito bacana seu trabalho com antivírus. 

Gostaria de entrar em contato contigo para conversarmos, é possível?

Att. Gustavo

**Comment by elDimasX** [comment]
Eae Gustavo, é possível sim mano!
Você pode entrar em contato comigo pelo Discord, que é esse: elDimas#8829

Em qua., 4 de mai. de 2022 às 09:16, Gustavo Gino Scotton <
***@***.***> escreveu:
